#   Question: 389. Find the Difference
# Difficulty: Easy
#       Tags: Bit Manipulation, Hash Table
'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
eg.
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

from collections import Counter


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        added = ''
        sCounter, tCounter = Counter(s), Counter(t)
        for k, v in tCounter.items():
            if k not in sCounter or sCounter[k] != tCounter[k]:
                added = k
                break

        return added

s = Solution()
print(s.findTheDifference("codee", "code"))
